package com.kyant.pixelmusic.api.newsongs

data class Album(
    val songs: List<Any>? = listOf(),
    val paid: Boolean? = false,
    val onSale: Boolean? = false,
    val description: String? = "",
    val tags: String? = "",
    val blurPicUrl: String? = "",
    val companyId: Int? = 0,
    val pic: Long? = 0,
    val company: String? = "",
    val commentThreadId: String? = "",
    val alias: List<String>? = listOf(),
    val artists: List<Artist>? = listOf(),
    val copyrightId: Int? = 0,
    val status: Int? = 0,
    val subType: String? = "",
    val briefDesc: String? = "",
    val picId: Long? = 0,
    val artist: Artist? = Artist(),
    val publishTime: Long? = 0,
    val picUrl: String? = "",
    val name: String? = "",
    val id: Long? = 0,
    val type: String? = "",
    val size: Int? = 0,
    val picId_str: String? = "",
    val transNames: List<String>? = listOf()
)