package com.kyant.pixelmusic.api.newsongs

data class Data(
    val starred: Boolean? = false,
    val popularity: Int? = 0,
    val starredNum: Int? = 0,
    val playedNum: Int? = 0,
    val dayPlays: Int? = 0,
    val hearTime: Int? = 0,
    val mp3Url: String? = "",
    val rtUrls: Any? = Any(),
    val duration: Int? = 0,
    val crbt: Any? = Any(),
    val bMusic: BMusic? = BMusic(),
    val rtUrl: Any? = Any(),
    val audition: Any? = Any(),
    val ringtone: String? = "",
    val disc: String? = "",
    val no: Int? = 0,
    val commentThreadId: String? = "",
    val alias: List<String>? = listOf(),
    val artists: List<Artist>? = listOf(),
    val score: Int? = 0,
    val copyrightId: Int? = 0,
    val position: Int? = 0,
    val status: Int? = 0,
    val fee: Int? = 0,
    val album: Album? = Album(),
    val mMusic: MMusic? = MMusic(),
    val lMusic: LMusic? = LMusic(),
    val copyFrom: String? = "",
    val hMusic: HMusic? = HMusic(),
    val mvid: Int? = 0,
    val ftype: Int? = 0,
    val rtype: Int? = 0,
    val rurl: Any? = Any(),
    val name: String? = "",
    val id: Long? = 0,
    val exclusive: Boolean? = false,
    val privilege: Privilege? = Privilege(),
    val transNames: List<String>? = listOf()
)